
config_version: 0.40

__build_info:
  rime_version: 1.11.2
  timestamps:
    default: 1717674678
    default.custom: 1718759502
    key_bindings: 1717674678
    key_bindings.custom: 0
    punctuation: 1717674678
    punctuation.custom: 0

schema_list:
  - schema: rime_zivon
  - schema: pinyin_simp
  #- schema: rime_mint            # 薄荷拼音
  #- schema: double_pinyin_flypy  # 小鹤双拼

switcher:
  caption: "【 方案选择 】"
  hotkeys:
    - Control+grave  #grave = `
    - Shift+Control+grave
    - Control+F4
    - Shift+Control+F4
  save_options:
    - full_shape  # 保留全角模式
    - ascii_punct # 保留西文模式
    - transcription     # 保留汉字简繁体选项
    - emoji_suggestion  # Emoji
  fold_options: true  # 折叠选项以节省空间，多方案时建议折叠 true ，一个方案建议展开 false
  abbreviate_options: true  # 对选项进行缩写
  option_list_separator: '／'  # 选项之间的分隔符

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: noop  # 按下 Caps Lock  键不做任何操作
    Control_L: noop  # 按下左 Control 键不做任何操作
    Control_R: noop  # 按下右 Control 键不做任何操作
    Eisu_toggle: clear #按下 esc 键 清除編码
    Shift_L: noop  # 按下左 shift 键不做任何操作
    Shift_R: commit_code   #按右shift直接上屏已输入内容
    #shift_r: inline_ascii  # 按下右 Shift 键会临时切换到西文模式

menu:
  page_size: 5  # 候选词个数

translator:
  enable_encoder: false  # 启用自动造词
  enable_sentence: false  # 启用自动句子输入
  enable_user_dict: false  # 启用用户词典_自动调频
  encode_commit_history: false   # 对已上屏的词语进行自动编码以提高下次输入的命中率


key_binder:
  bindings:
    # 切换状态 
    #- {accept: "Shift+space", toggle: full_shape, when: always}
    - {accept: "Control+period", toggle: ascii_punct, when: always}
    - {accept: "Control+d", send: "Shift+Delete", when: composing}  # 删除到行尾
    # 翻页
    - {accept: "Control+n", send: Page_Up, when: composing}
    - {accept: "Control+m", send: Page_Down, when: composing}
    - {accept: "Control+e", send: Page_Up, when: composing}
    - {accept: "Control+r", send: Page_Down, when: composing}
    - {accept: "Control+k", send: Up, when: composing}
    - {accept: "Control+j", send: Down, when: composing}

recognizer:
  # 定义识别码的正则表达式规则
  patterns:
    email: "^[a-z][-_.0-9a-z]*@.*$"  # 匹配电子邮件地址
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"  # 匹配大写字母开头的字符串
    url: "^(www[.]|https?:|ftp:|mailto:).*$|^[a-z]+[.].+$"  # 匹配 URL 或域名


punctuator:
  full_shape:
    " ": {commit: "　"}
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": ["＃", "⌘"]
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
    "%": ["％", "°", "℃"]
    "&": "＆"
    "'": {pair: ["‘", "’"]}
    "(": "（"
    ")": "）"
    "*": ["＊", "·", "・", "×", "※", "❂"]
    "+": "＋"
    ",": {commit: "，"}
    "-": "－"
    .: {commit: "。"}
    "/": ["／", "÷"]
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": ["《", "〈", "«", "‹"]
    "=": "＝"
    ">": ["》", "〉", "»", "›"]
    "?": {commit: "？"}
    "@": ["＠", "☯"]
    "[": ["「", "【", "〔", "［"]
    "\\": ["、", "＼"]
    "]": ["」", "】", "〕", "］"]
    "^": {commit: "……"}
    _: "——"
    "`": "｀"
    "{": ["『", "〖", "｛"]
    "|": ["·", "｜", "§", "¦"]
    "}": ["』", "〗", "｝"]
    "~": "～"
  half_shape:
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": "#"
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
    "%": ["%", "％", "°", "℃"]
    "&": "&"
    "'": {pair: ["‘", "’"]}
    "(": "（"
    ")": "）"
    "*": ["*", "＊", "·", "・", "×", "※", "❂"]
    "+": "+"
    ",": {commit: "，"}
    "-": "-"
    .: {commit: "。"}
    "/": ["、", "/", "／", "÷"]
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": ["《", "〈", "«", "‹"]
    "=": "="
    ">": ["》", "〉", "»", "›"]
    "?": {commit: "？"}
    "@": "@"
    "[": ["「", "【", "〔", "［"]
    "\\": ["、", "\\", "＼"]
    "]": ["」", "】", "〕", "］"]
    "^": {commit: "……"}
    _: "——"
    "`": "`"
    "{": ["『", "〖", "｛"]
    "|": ["·", "|", "｜", "§", "¦"]
    "}": ["』", "〗", "｝"]
    "~": ["~", "～"]



